//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolWS.Homolog.SessionManager
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogonRequestData", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient")]
    public partial class LogonRequestData : object
    {
        
        private GolWS.Homolog.SessionManager.ExtensionDataObject ExtensionData1Field;
        
        private string DomainCodeField;
        
        private string AgentNameField;
        
        private string PasswordField;
        
        private string LocationCodeField;
        
        private string RoleCodeField;
        
        private string TerminalInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public GolWS.Homolog.SessionManager.ExtensionDataObject ExtensionData1
        {
            get
            {
                return this.ExtensionData1Field;
            }
            set
            {
                this.ExtensionData1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DomainCode
        {
            get
            {
                return this.DomainCodeField;
            }
            set
            {
                this.DomainCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AgentName
        {
            get
            {
                return this.AgentNameField;
            }
            set
            {
                this.AgentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LocationCode
        {
            get
            {
                return this.LocationCodeField;
            }
            set
            {
                this.LocationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RoleCode
        {
            get
            {
                return this.RoleCodeField;
            }
            set
            {
                this.RoleCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TerminalInfo
        {
            get
            {
                return this.TerminalInfoField;
            }
            set
            {
                this.TerminalInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient")]
    public partial class ExtensionDataObject : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BWSSession", Namespace="http://bws.voegol.com.br/Common")]
    public partial class BWSSession : object
    {
        
        private string AgencyCodeField;
        
        private string AgentNameField;
        
        private string DomainCodeField;
        
        private string LastNameField;
        
        private string FirstNameField;
        
        private long PersonIDField;
        
        private string RoleCodeField;
        
        private string SignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AgencyCode
        {
            get
            {
                return this.AgencyCodeField;
            }
            set
            {
                this.AgencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AgentName
        {
            get
            {
                return this.AgentNameField;
            }
            set
            {
                this.AgentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DomainCode
        {
            get
            {
                return this.DomainCodeField;
            }
            set
            {
                this.DomainCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long PersonID
        {
            get
            {
                return this.PersonIDField;
            }
            set
            {
                this.PersonIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RoleCode
        {
            get
            {
                return this.RoleCodeField;
            }
            set
            {
                this.RoleCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferSessionResponseData", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient")]
    public partial class TransferSessionResponseData : object
    {
        
        private GolWS.Homolog.SessionManager.ExtensionDataObject ExtensionData1Field;
        
        private string SignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public GolWS.Homolog.SessionManager.ExtensionDataObject ExtensionData1
        {
            get
            {
                return this.ExtensionData1Field;
            }
            set
            {
                this.ExtensionData1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient", ConfigurationName="GolWS.Homolog.SessionManager.ISessionManagerClient")]
    public interface ISessionManagerClient
    {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento agencyCode do namespace http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/ChangePassword", ReplyAction="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/ChangePasswordResponse")]
        GolWS.Homolog.SessionManager.ChangePasswordResponse ChangePassword(GolWS.Homolog.SessionManager.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/ChangePassword", ReplyAction="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/ChangePasswordResponse")]
        System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.ChangePasswordResponse> ChangePasswordAsync(GolWS.Homolog.SessionManager.ChangePasswordRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento agencyCode do namespace http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/Logon", ReplyAction="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/LogonResponse")]
        GolWS.Homolog.SessionManager.LogonResponse Logon(GolWS.Homolog.SessionManager.LogonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/Logon", ReplyAction="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/LogonResponse")]
        System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.LogonResponse> LogonAsync(GolWS.Homolog.SessionManager.LogonRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento session do namespace http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/Logout", ReplyAction="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/LogoutResponse")]
        GolWS.Homolog.SessionManager.LogoutResponse Logout(GolWS.Homolog.SessionManager.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/Logout", ReplyAction="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/LogoutResponse")]
        System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.LogoutResponse> LogoutAsync(GolWS.Homolog.SessionManager.LogoutRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento agencyCode do namespace http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/TransferSession", ReplyAction="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/TransferSessionResponse")]
        GolWS.Homolog.SessionManager.TransferSessionResponse TransferSession(GolWS.Homolog.SessionManager.TransferSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/TransferSession", ReplyAction="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient/I" +
            "SessionManagerClient/TransferSessionResponse")]
        System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.TransferSessionResponse> TransferSessionAsync(GolWS.Homolog.SessionManager.TransferSessionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient", Order=0)]
        public GolWS.Homolog.SessionManager.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest()
        {
        }
        
        public ChangePasswordRequest(GolWS.Homolog.SessionManager.ChangePasswordRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient")]
    public partial class ChangePasswordRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agencyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GolWS.Homolog.SessionManager.LogonRequestData logonRequest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public ChangePasswordRequestBody()
        {
        }
        
        public ChangePasswordRequestBody(string agencyCode, GolWS.Homolog.SessionManager.LogonRequestData logonRequest, string newPassword)
        {
            this.agencyCode = agencyCode;
            this.logonRequest = logonRequest;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient", Order=0)]
        public GolWS.Homolog.SessionManager.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse()
        {
        }
        
        public ChangePasswordResponse(GolWS.Homolog.SessionManager.ChangePasswordResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangePasswordResponseBody
    {
        
        public ChangePasswordResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logon", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient", Order=0)]
        public GolWS.Homolog.SessionManager.LogonRequestBody Body;
        
        public LogonRequest()
        {
        }
        
        public LogonRequest(GolWS.Homolog.SessionManager.LogonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient")]
    public partial class LogonRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agencyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GolWS.Homolog.SessionManager.LogonRequestData logonRequest;
        
        public LogonRequestBody()
        {
        }
        
        public LogonRequestBody(string agencyCode, GolWS.Homolog.SessionManager.LogonRequestData logonRequest)
        {
            this.agencyCode = agencyCode;
            this.logonRequest = logonRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogonResponse", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient", Order=0)]
        public GolWS.Homolog.SessionManager.LogonResponseBody Body;
        
        public LogonResponse()
        {
        }
        
        public LogonResponse(GolWS.Homolog.SessionManager.LogonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient")]
    public partial class LogonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GolWS.Homolog.SessionManager.BWSSession LogonResult;
        
        public LogonResponseBody()
        {
        }
        
        public LogonResponseBody(GolWS.Homolog.SessionManager.BWSSession LogonResult)
        {
            this.LogonResult = LogonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient", Order=0)]
        public GolWS.Homolog.SessionManager.LogoutRequestBody Body;
        
        public LogoutRequest()
        {
        }
        
        public LogoutRequest(GolWS.Homolog.SessionManager.LogoutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient")]
    public partial class LogoutRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GolWS.Homolog.SessionManager.BWSSession session;
        
        public LogoutRequestBody()
        {
        }
        
        public LogoutRequestBody(GolWS.Homolog.SessionManager.BWSSession session)
        {
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient", Order=0)]
        public GolWS.Homolog.SessionManager.LogoutResponseBody Body;
        
        public LogoutResponse()
        {
        }
        
        public LogoutResponse(GolWS.Homolog.SessionManager.LogoutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogoutResponseBody
    {
        
        public LogoutResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransferSession", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient", Order=0)]
        public GolWS.Homolog.SessionManager.TransferSessionRequestBody Body;
        
        public TransferSessionRequest()
        {
        }
        
        public TransferSessionRequest(GolWS.Homolog.SessionManager.TransferSessionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient")]
    public partial class TransferSessionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agencyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GolWS.Homolog.SessionManager.BWSSession session;
        
        public TransferSessionRequestBody()
        {
        }
        
        public TransferSessionRequestBody(string agencyCode, GolWS.Homolog.SessionManager.BWSSession session)
        {
            this.agencyCode = agencyCode;
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransferSessionResponse", Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient", Order=0)]
        public GolWS.Homolog.SessionManager.TransferSessionResponseBody Body;
        
        public TransferSessionResponse()
        {
        }
        
        public TransferSessionResponse(GolWS.Homolog.SessionManager.TransferSessionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.navitaire.com/ClientServices/SessionManager/SessionManagerClient")]
    public partial class TransferSessionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GolWS.Homolog.SessionManager.TransferSessionResponseData TransferSessionResult;
        
        public TransferSessionResponseBody()
        {
        }
        
        public TransferSessionResponseBody(GolWS.Homolog.SessionManager.TransferSessionResponseData TransferSessionResult)
        {
            this.TransferSessionResult = TransferSessionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISessionManagerClientChannel : GolWS.Homolog.SessionManager.ISessionManagerClient, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SessionManagerClientClient : System.ServiceModel.ClientBase<GolWS.Homolog.SessionManager.ISessionManagerClient>, GolWS.Homolog.SessionManager.ISessionManagerClient
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SessionManagerClientClient(EndpointConfiguration endpointConfiguration) : 
                base(SessionManagerClientClient.GetBindingForEndpoint(endpointConfiguration), SessionManagerClientClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagerClientClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SessionManagerClientClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagerClientClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SessionManagerClientClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagerClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GolWS.Homolog.SessionManager.ChangePasswordResponse GolWS.Homolog.SessionManager.ISessionManagerClient.ChangePassword(GolWS.Homolog.SessionManager.ChangePasswordRequest request)
        {
            return base.Channel.ChangePassword(request);
        }
        
        public void ChangePassword(string agencyCode, GolWS.Homolog.SessionManager.LogonRequestData logonRequest, string newPassword)
        {
            GolWS.Homolog.SessionManager.ChangePasswordRequest inValue = new GolWS.Homolog.SessionManager.ChangePasswordRequest();
            inValue.Body = new GolWS.Homolog.SessionManager.ChangePasswordRequestBody();
            inValue.Body.agencyCode = agencyCode;
            inValue.Body.logonRequest = logonRequest;
            inValue.Body.newPassword = newPassword;
            GolWS.Homolog.SessionManager.ChangePasswordResponse retVal = ((GolWS.Homolog.SessionManager.ISessionManagerClient)(this)).ChangePassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.ChangePasswordResponse> GolWS.Homolog.SessionManager.ISessionManagerClient.ChangePasswordAsync(GolWS.Homolog.SessionManager.ChangePasswordRequest request)
        {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.ChangePasswordResponse> ChangePasswordAsync(string agencyCode, GolWS.Homolog.SessionManager.LogonRequestData logonRequest, string newPassword)
        {
            GolWS.Homolog.SessionManager.ChangePasswordRequest inValue = new GolWS.Homolog.SessionManager.ChangePasswordRequest();
            inValue.Body = new GolWS.Homolog.SessionManager.ChangePasswordRequestBody();
            inValue.Body.agencyCode = agencyCode;
            inValue.Body.logonRequest = logonRequest;
            inValue.Body.newPassword = newPassword;
            return ((GolWS.Homolog.SessionManager.ISessionManagerClient)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GolWS.Homolog.SessionManager.LogonResponse GolWS.Homolog.SessionManager.ISessionManagerClient.Logon(GolWS.Homolog.SessionManager.LogonRequest request)
        {
            return base.Channel.Logon(request);
        }
        
        public GolWS.Homolog.SessionManager.BWSSession Logon(string agencyCode, GolWS.Homolog.SessionManager.LogonRequestData logonRequest)
        {
            GolWS.Homolog.SessionManager.LogonRequest inValue = new GolWS.Homolog.SessionManager.LogonRequest();
            inValue.Body = new GolWS.Homolog.SessionManager.LogonRequestBody();
            inValue.Body.agencyCode = agencyCode;
            inValue.Body.logonRequest = logonRequest;
            GolWS.Homolog.SessionManager.LogonResponse retVal = ((GolWS.Homolog.SessionManager.ISessionManagerClient)(this)).Logon(inValue);
            return retVal.Body.LogonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.LogonResponse> GolWS.Homolog.SessionManager.ISessionManagerClient.LogonAsync(GolWS.Homolog.SessionManager.LogonRequest request)
        {
            return base.Channel.LogonAsync(request);
        }
        
        public System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.LogonResponse> LogonAsync(string agencyCode, GolWS.Homolog.SessionManager.LogonRequestData logonRequest)
        {
            GolWS.Homolog.SessionManager.LogonRequest inValue = new GolWS.Homolog.SessionManager.LogonRequest();
            inValue.Body = new GolWS.Homolog.SessionManager.LogonRequestBody();
            inValue.Body.agencyCode = agencyCode;
            inValue.Body.logonRequest = logonRequest;
            return ((GolWS.Homolog.SessionManager.ISessionManagerClient)(this)).LogonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GolWS.Homolog.SessionManager.LogoutResponse GolWS.Homolog.SessionManager.ISessionManagerClient.Logout(GolWS.Homolog.SessionManager.LogoutRequest request)
        {
            return base.Channel.Logout(request);
        }
        
        public void Logout(GolWS.Homolog.SessionManager.BWSSession session)
        {
            GolWS.Homolog.SessionManager.LogoutRequest inValue = new GolWS.Homolog.SessionManager.LogoutRequest();
            inValue.Body = new GolWS.Homolog.SessionManager.LogoutRequestBody();
            inValue.Body.session = session;
            GolWS.Homolog.SessionManager.LogoutResponse retVal = ((GolWS.Homolog.SessionManager.ISessionManagerClient)(this)).Logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.LogoutResponse> GolWS.Homolog.SessionManager.ISessionManagerClient.LogoutAsync(GolWS.Homolog.SessionManager.LogoutRequest request)
        {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.LogoutResponse> LogoutAsync(GolWS.Homolog.SessionManager.BWSSession session)
        {
            GolWS.Homolog.SessionManager.LogoutRequest inValue = new GolWS.Homolog.SessionManager.LogoutRequest();
            inValue.Body = new GolWS.Homolog.SessionManager.LogoutRequestBody();
            inValue.Body.session = session;
            return ((GolWS.Homolog.SessionManager.ISessionManagerClient)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GolWS.Homolog.SessionManager.TransferSessionResponse GolWS.Homolog.SessionManager.ISessionManagerClient.TransferSession(GolWS.Homolog.SessionManager.TransferSessionRequest request)
        {
            return base.Channel.TransferSession(request);
        }
        
        public GolWS.Homolog.SessionManager.TransferSessionResponseData TransferSession(string agencyCode, GolWS.Homolog.SessionManager.BWSSession session)
        {
            GolWS.Homolog.SessionManager.TransferSessionRequest inValue = new GolWS.Homolog.SessionManager.TransferSessionRequest();
            inValue.Body = new GolWS.Homolog.SessionManager.TransferSessionRequestBody();
            inValue.Body.agencyCode = agencyCode;
            inValue.Body.session = session;
            GolWS.Homolog.SessionManager.TransferSessionResponse retVal = ((GolWS.Homolog.SessionManager.ISessionManagerClient)(this)).TransferSession(inValue);
            return retVal.Body.TransferSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.TransferSessionResponse> GolWS.Homolog.SessionManager.ISessionManagerClient.TransferSessionAsync(GolWS.Homolog.SessionManager.TransferSessionRequest request)
        {
            return base.Channel.TransferSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GolWS.Homolog.SessionManager.TransferSessionResponse> TransferSessionAsync(string agencyCode, GolWS.Homolog.SessionManager.BWSSession session)
        {
            GolWS.Homolog.SessionManager.TransferSessionRequest inValue = new GolWS.Homolog.SessionManager.TransferSessionRequest();
            inValue.Body = new GolWS.Homolog.SessionManager.TransferSessionRequestBody();
            inValue.Body.agencyCode = agencyCode;
            inValue.Body.session = session;
            return ((GolWS.Homolog.SessionManager.ISessionManagerClient)(this)).TransferSessionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionManagerClient))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionManagerClient1))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionManagerClient))
            {
                return new System.ServiceModel.EndpointAddress("https://hom-bws34.voegol.com.br/BWS/SessionManagerClient.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionManagerClient1))
            {
                return new System.ServiceModel.EndpointAddress("https://hom-bws34.voegol.com.br/BWS/SessionManagerClient.svc");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISessionManagerClient,
            
            BasicHttpBinding_ISessionManagerClient1,
        }
    }
}
